services:
  mysql-delivery:
    container_name: mysql-delivery
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: deliverydb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 12345
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - local-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  mysql-courier:
    container_name: mysql-courier
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: courierdb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 12345
    volumes:
      - mysql-courier-data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - local-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  phpmyadmin:
    container_name: phpmyadmin-algadelivery
    image: phpmyadmin:latest
    platform: linux/amd64
    depends_on:
      mysql-delivery:
        condition: service_healthy
      mysql-courier:
        condition: service_healthy
    environment:
      PMA_HOSTS: mysql-delivery,mysql-courier
      PMA_VERBOSES: Banco_Delivery,Banco_Courier
      PMA_ARBITRARY: 1
    ports:
      - 8083:80
    networks:
      - local-network

  kafka:
    image: apache/kafka:4.1.1
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9090,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9091
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/apache/kafka
    networks:
      - local-network

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8084:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: algadelivery-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9090
    networks:
      - local-network

volumes:
  mysql-data:
  mysql-courier-data:
  kafka-data:

networks:
  local-network:
    driver: bridge