server:
  port: 8082

spring:
  application:
    name: Courier-Management

  datasource:
    url: jdbc:mysql://localhost:3307/courierdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: mysql #root #(caso execute localmente)
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: courier-management
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'
        spring.json.type.mapping:
          delivery-placed-event:com.algaworks.algadelivery.courier.management.infrastructure.event.DeliveryPlacedIntegrationEvent,
          delivery-picked-up-event:com.fasterxml.jackson.databind.JsonNode,
          delivery-fulfilled-event:com.algaworks.algadelivery.courier.management.infrastructure.event.DeliveryFulfilledIntegrationEvent
